[build]
  command = "npm run build:netlify"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"
  NETLIFY = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects para Next.js App Router
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

[functions]
  directory = ".netlify/functions"

# Configuración específica para Next.js
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
